# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
            ],
        ),
    ]
