# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170712_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry',
            field=models.CharField(max_length=2000),
        ),
    ]
