# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20170713_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry',
            field=models.CharField(max_length=2500),
        ),
    ]
